[package]
name = "minigram-1-ui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "scale"
required-features = ["simulator"]

[[bin]]
name = "main_menu"
required-features = ["simulator"]

[[bin]]
name = "settings"
required-features = ["simulator"]

[[bin]]
name = "settings_menu"
required-features = ["simulator"]

[dependencies]
embedded-graphics = "0.8.1"
embedded-graphics-simulator = { version = "0.8.0", optional = true }
embedded-text = "0.7.3"
u8g2-fonts = { version = "0.7.2", features = ["embedded_graphics_textstyle"] }
embedded-mogeefont = "0.1.0"
defmt = { version = "1.0.1", optional = true }
heapless = "0.9.2"
embedded-graphics-colorcast = "0.1.1"

[build-dependencies]
embedded-graphics = "0.8.1"
tinybmp = "0.7.0"

[features]
default = []
defmt = ["dep:defmt"]
simulator = ["dep:embedded-graphics-simulator"]
